var nome = "Gabriel Dupim";
//var idade = 16;
//var idade2 = 10;
var n1 = 5;
var n2 = 3;
var frase = "Brasil é o melhor time do mundo.";
//var idade = "16";
//var idade2 = "10";

//alert("Bem-vindo " + nome);
//alert(nome + " tem idade de " + idade + " anos.");
//alert(idade + idade2);
console.log(nome);
//console.log(idade + idade2);
console.log(n1 * n2);
//console.log(n1 * idade);
console.log(frase.replace("Brasil", "Alemanha"));
console.log(frase.toUpperCase());
console.log(frase.toLowerCase());
//alert(frase.replace("Brasil", "Japão"));